### ISSUE TITLE
June Session: TulsaPy Coding Dojo

### ISSUE THREAD

**Issue by rtimoshenko** [tulsawebdevs/tasks#22]
We'll split off into our own group and take turns rotating pairs and learning how to solve a simple problem in Python. :)

**Comment by groovecoder** [comment]
Hey Ron. Do you have permission/access to add this to the wiki page yourself? (I assume you meant July session?)

https://github.com/tulsawebdevs/tasks/wiki/July-2016-Meeting

**Comment by rtimoshenko** [comment]
Looks like I do! I'll add it directly in the future; thanks Luke!
