### ISSUE TITLE
Add talk voting app to meeting wiki page

### ISSUE THREAD

**Issue by groovecoder** [tulsawebdevs/tasks#4]
Link to https://twdtalks.herokuapp.com/# in blog post and on Facebook and G+ events.

**Comment by mrmakeit** [comment]
https://github.com/mrmakeit/TWDTalks/issues/2 
This should be changed before adding to the wiki.

Also, is this still an active item? or has it just never been removed?

**Comment by groovecoder** [comment]
We can close this. We now use GitHub issues to file talks for meetings and we just ask people at the meeting how many want to go to each talk.
