### ISSUE TITLE
March Session:

### ISSUE THREAD

**Issue by zerokarmaleft** [tulsawebdevs/tasks#7]
* Tulsa Lambda Lounge
  * Greg Tatum (@TatumCreative): TBA

**Comment by groovecoder** [comment]
Added: http://tulsawebdevs.org/blog/2015/03/03/march-meeting-5/

**Comment by TatumCreative** [comment]
Talk title:
Killing JavaScript's `this` with practical functional programming

**Comment by jgmize** [comment]
Really looking forward to `this` talk, @TatumCreative :D

**Comment by groovecoder** [comment]
![joke-catch](https://cloud.githubusercontent.com/assets/71928/6484290/41337d48-c240-11e4-9941-30272cf80c26.gif)
