### ISSUE TITLE
May Session: Continuous Delivery with Docker, Deis, and Jenkins at Mozilla

### ISSUE THREAD

**Issue by jgmize** [tulsawebdevs/tasks#9]

**Comment by groovecoder** [comment]
So far we're trying to kick up some talks about Energy technology, to lead into Startup Weekend Energy happening May 1-3. Okay to punt this topic to May?

**Comment by jgmize** [comment]
> Okay to punt this topic to May?

Sure. Updated description.

cc @zerokarmaleft

**Comment by zerokarmaleft** [comment]
+1
